# Contributors:- 


### 1. Protyush Kumar Das (pdas2s)
 
### 2. Somesh Devagekar (sdevag2s)

### 3. Gautam Kumar Jain (gjain2s)


# Build a spam classifier using Naive Bayes

## Project Description: 
- There are three datasets for training: TrainDataset1.csv, TrainDataset2.csv and TrainDataset3.txt. Each dataset contains short messages with the labels (ham or spam). 
- Analyse, clean and visualise these datasets.
- Combine them into one big data set for the training
- Use this dataset in order to build your own Naive Bayes classifier. (You can either use existing Naive Bayes from sklearn or build your own one)
- Verify your Classifier using new messages (create your own messages or use the messages from the TestDataset.csv dataset).

## Project Duration: 2 weeks
## Project Deliverables:
1. End of the first week do Data preprocessing: 
    - Load the dataset using pandas, 
    - Analysis it for this you will need to process the text, namely remove punctuation and stopwords, and then create a list of clean text words. (Research how to do this) 
    - Visualise the results
    - Prepare the pre-processed data for the usage by Naive Bayes Classifier
2. End of the second week:
    - Train the classifier,
    - Validate it, build confusion matrix, analyse its results
    - Apply it to new test messages,
    - Try to cheat the classifier by adding "good words" to the end of test message.

You can use the following link can be used as guidance for implementation:
https://towardsdatascience.com/spam-filtering-using-naive-bayes-98a341224038

**Loading the data and concatenating into one**

In [19]:
import pandas as pd
import numpy as np
import string
import matplotlib.pyplot as plt


D_1=pd.read_csv('TrainDataset1.csv')
D_2=pd.read_csv('TrainDataset2.csv')
D_2.rename(columns={'v1': 'type', 'v2': 'text'}, inplace=True)
D_3=pd.read_csv('TrainDataset3.txt', sep=r"\t+", header=None ,engine="python")
D_3=D_3.rename(columns={0: "type", 1: "text"})

TrainDataset=pd.concat([D_3,D_2,D_1])
TrainDataset.head()

type                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

**Cleaning and labeling loaded data concatenated into one**

In [20]:
TrainDataset = TrainDataset.sample(frac=1).reset_index(drop=True) # scattering dataset increase randomness
type_of_text = list(TrainDataset["type"])
labels = list()
for item in type_of_text:
    if item == "ham":
        labels.append(0)
    else:
        labels.append(1)

        
TrainDataset["label"] = labels

def remove_punctuations(text):
    for punctuation in string.punctuation:
        text = text.replace(punctuation, '')
    return text


TrainDataset['text'] = TrainDataset['text'].apply(remove_punctuations)
TrainDataset


type                                               text  label
0       ham  Kind of Just missed train cos of asthma attack...      0
1      spam  Get 3 Lions England tone reply lionm 4 mono or...      1
2       ham         Im working technical support voice process      0
3       ham  Up to u u wan come then come lor But i din c a...      0
4      spam  WIN We have a winner Mr T Foley won an iPod Mo...      1
5       ham  Okie Ì wan meet at bishan Cos me at bishan now...      0
6       ham  Ü got wat to buy tell us then ü no need to com...      0
7       ham  Stop the story Ive told him ive returned it an...      0
8       ham  wiskey Brandy Rum Gin Beer Vodka Scotch Shampa...      0
9       ham       Im in office now  I will call you  ltgt  min      0
10      ham  Ummmawill call after check inour life will beg...      0
11      ham                       No need for the drug anymore      0
12     spam  Gr8 new service  live sex video chat on your m...      1
13      ham                       Mm i had my food da from out      0
14     spam  Urgent UR awarded a complimentary trip to Euro...      1
15      ham                          Nicenicehow is it working      0
16      ham         Oh for fucks sake shes in like tallahassee      0
17     spam  Twinks bears scallies skins and jocks are call...      1
18      ham  No dahe is stupid daalways sending like thisdo...      0
19      ham  Yeah theres quite a bit left Ill swing by tomo...      0
20      ham                             I liked your new house      0
21      ham                             Should I be stalking u      0
22      ham  Say this slowly GODI LOVE YOU  I NEED YOUCLEAN...      0
23      ham  I think that tantrums finished so yeah Ill be ...      0
24      ham     Aiya we discuss later lar Pick u up at 4 is it      0
25      ham  Dont necessarily expect it to be done before y...      0
26      ham  My stomach has been thru so much trauma I swea...      0
27      ham        U dun say so early hor U c already then say      0
28      ham  Roger that We‰Û÷re probably going to rem in ab...      0
29      ham  Aight sounds good When do you want me to come ...      0
...     ...                                                ...    ...
15560   ham                        Dont you have message offer      0
15561   ham                                      Which channel      0
15562   ham               Should I head straight there or what      0
15563   ham  Erm I thought the contract ran out the4th of o...      0
15564   ham  Where are you  What do you do  How can you sta...      0
15565   ham  Lol  Oh no babe I wont be sliding into your pl...      0
15566   ham                              You got called a tool      0
15567  spam  u r subscribed 2 TEXTCOMP 250 wkly comp 1st wk...      1
15568   ham  ltgt of pple marry with their lovers becz they...      0
15569   ham                      Sorry pa i dont knw who ru pa      0
15570   ham  Cant think of anyone with  spare room off  top...      0
15571   ham                              Can you open the door      0
15572   ham  And stop wondering wow is she ever going to st...      0
15573   ham  Thank you so much When we skyped wit kz and su...      0
15574   ham  Ahhhhjust woken uphad a bad dream about u thos...      0
15575   ham  I taught that Ranjith sir called me So only i ...      0
15576   ham  Asking do u knw them or nt May be ur frnds or ...      0
15577   ham                            What not under standing      0
15578   ham                  Can u send me a copy of da report      0
15579   ham  Sorry chikku my cell got some problem thts y i...      0
15580   ham                                Gd luck 4 ur exams       0
15581   ham                Pls i wont belive godnot only jesus      0
15582   ham  Hey iouri gave me your number Im wylie ryans f...      0
15583   ham                Hi where you You in home or calicut      0
15584   ham                       I hope your pee burns tonite      0
15585   ham  Ooh 

## Training the classifier

In [21]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.cross_validation import train_test_split

#parsing the dataset into equal labels and mails. 
X = TrainDataset.text
y = TrainDataset.label

X_train , X_test, y_train , y_test = train_test_split(X,y)

#vectorizing the words in the text 
vectorizer = CountVectorizer()
counts = vectorizer.fit_transform(X_train.values)

classifier = MultinomialNB()
targets = y_train.values 

classifier.fit(counts, targets)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [23]:
test_count = vectorizer.transform(X_test)
predictions = classifier.predict(test_count)
predictions

array([0, 0, 0, ..., 0, 0, 0])

## Confusion Matrix

In [15]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,predictions)

array([[4791,   21],
       [  17,  730]])

In [24]:
from sklearn.metrics import f1_score

f1_score(y_test,predictions, average = 'binary')

0.9586935638808837

## Validation on Test dataset

In [64]:
V_test =pd.read_csv('TestDataset.csv')
# V_test.head()

# cleaning validation dataset 
def remove_punctuations(text):
    for punctuation in string.punctuation:
        text = text.replace(punctuation, '')
    return text


V_test['v2'] = V_test['v2'].apply(remove_punctuations)

V_examples = V_test.v2

#vectorizing the text in the test dataset
V_count = vectorizer.transform(V_examples)
V_predictions = classifier.predict(V_count)

V_predictions[0:20]

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

## Creating a custom message to cheat the algorithm by adding good words in the end. 


In [65]:
cheat_example = V_examples[3] + 'I appreciate your care'

print(cheat_example)

cheat_count = vectorizer.transform(cheat_example)
cheat_prediction = classifier.predict(cheat_count)

print('\n')
print(cheat_prediction)


Congrats 2 mobile 3G Videophones R yours call 09061744553 now videochat wid ur mates play java games Dload polyH music noline rentl bx420 ip4 5we 150pmI appreciate your care


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


We took the $\textbf{fourth example} $ from the test dataset and add some good words at the end of the text and we can see that before it was predicted by the classifier as 'SPAM' and now it is a 'HAM' 